<a href="https://colab.research.google.com/github/SaimManzoor49/tensorflow/blob/main/TensorFlow_Tensors_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,3])
print(tensor_one_d)

tf.Tensor([1 3], shape=(2,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant(
    [
        [1,2],
        [3,4],
        [4,5]
    ]
)
print(tensor_two_d)

tf.Tensor(
[[1 2]
 [3 4]
 [4 5]], shape=(3, 2), dtype=int32)


In [ ]:
tensor_three_d = tf.constant(
    [
        [
            [1,2],
            [1,3],
            [1,4],
        ],
        [
            [2,2],
            [3,3],
            [4,4],
        ],
    ]
)
print(tensor_three_d)

tf.Tensor(
[[[1 2]
  [1 3]
  [1 4]]

 [[2 2]
  [3 3]
  [4 4]]], shape=(2, 3, 2), dtype=int32)


In [ ]:
tensor_four_d = tf.constant(
    [
        [
            [
                [1,2],
                [3,2]
            ],
            [
                [23,23],
                [23,2321]
            ]
        ],
        [
            [
                [1,3242],
                [3,2]
            ],
            [
                [21343,23],
                [23,2321]
            ]
        ]
    ]
)
print(tensor_four_d)

tf.Tensor(
[[[[    1     2]
   [    3     2]]

  [[   23    23]
   [   23  2321]]]


 [[[    1  3242]
   [    3     2]]

  [[21343    23]
   [   23  2321]]]], shape=(2, 2, 2, 2), dtype=int32)


In [ ]:
print(f'tensor zero d shape{tensor_zero_d.shape}')
print(f'tensor one d shape{tensor_one_d.shape}')
print(f'tensor two d shape{tensor_two_d.shape}')
print(f'tensor three d shape{tensor_three_d.shape}')
print(f'tensor four d shape{tensor_four_d.shape}')

tensor zero d shape()
tensor one d shape(2,)
tensor two d shape(3, 2)
tensor three d shape(2, 3, 2)
tensor four d shape(2, 2, 2, 2)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [ ]:
np_to_tensor = tf.convert_to_tensor(np_array)
print(np_to_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [ ]:
fill_tensor = tf.fill([2,3],99)
print(fill_tensor)

tf.Tensor(
[[99 99 99]
 [99 99 99]], shape=(2, 3), dtype=int32)


In [ ]:
ones = tf.ones([2,3],dtype=tf.dtypes.float32)
print(ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
randoms = tf.random.normal(
    [2,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(randoms0)

tf.Tensor(
[[ 1.1192895   1.0842891  -0.6387086 ]
 [ 0.03725942  0.5556142   0.47480613]], shape=(2, 3), dtype=float32)


In [ ]:
uniform_tensors = tf.random.uniform(
    [2,3],
    minval=0,
    maxval=None, # by default it is set to 1
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(uniform_tensors)

tf.Tensor(
[[0.2354865  0.8461753  0.46223438]
 [0.23446548 0.705001   0.209463  ]], shape=(2, 3), dtype=float32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))
print(tf.random.uniform([3],minval=0,maxval=5,dtype=tf.dtypes.int32,seed=10,name=None))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
A = np.array(
    [
        [1,2,3],
        [4,5,6],
        [1,2,3],
    ]
)
B = np.array(
    [
        [11,22,33],
        [42,52,62],
        [11,32,32],
    ]
)

print(np.einsum("ij,jk -> ik",A,B)) # Matrix multiplication

[[128 222 253]
 [320 540 634]
 [128 222 253]]


In [ ]:
A = np.array(
    [
        [1,2,3],
        [4,5,6],
        [1,2,3],
    ]
)

print(np.einsum("ij -> ji",A)) # Matrix transpose

[[1 4 1]
 [2 5 2]
 [3 6 3]]


In [ ]:
u = tf.constant([1,2])
v = tf.constant([3,4])
print(tf.einsum('i,j -> ',u,v)) # dot product

tf.Tensor(
[[3 4]
 [6 8]], shape=(2, 2), dtype=int32)


In [ ]:
u = tf.constant([1,2])
v = tf.constant([3,4])
print(tf.einsum('i,j -> ij',u,v)) # cross product

tf.Tensor(
[[3 4]
 [6 8]], shape=(2, 2), dtype=int32)


In [ ]:
ones = tf.ones([3,3])
m = tf.reshape(tf.range(9), [3,3])
print(m)
print(tf.einsum('ii->i',m))

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor([0 4 8], shape=(3,), dtype=int32)


In [ ]:
s = tf.random.normal(shape=[7,5,3])
t = tf.random.normal(shape=[7,3,2])
e = tf.einsum('bij,bjk->bik', s, t)
# output[a,i,k] = sum_j s[a,i,j] * t[a, j, k]
print(e) # Batch Matrix Multiplication

tf.Tensor(
[[[-0.8413153   4.1956854 ]
  [ 5.1574116   1.1052887 ]
  [14.047793    0.36372095]]

 [[ 0.23557524 -0.25815493]
  [-0.29909948 -0.09841295]
  [ 0.07528932  0.23703322]]

 [[ 0.334353   -0.33635846]
  [ 0.33007073 -0.08020963]
  [ 2.0963485  -3.230741  ]]

 [[-0.6348581  -0.73232263]
  [-3.561839    2.6496143 ]
  [-0.02551105  0.0197349 ]]

 [[-0.5423168  -0.2530426 ]
  [-0.4307006  -1.142095  ]
  [-1.3113564  -0.5867977 ]]

 [[-3.5365663  -0.4593049 ]
  [-0.52530634  0.09930498]
  [ 0.08882731  0.496365  ]]

 [[ 6.3434715  -2.0845594 ]
  [-1.1916043  -1.9852884 ]
  [ 0.04790717  1.1770179 ]]], shape=(7, 3, 2), dtype=float32)
